### ISSUE TITLE
"Unable to find integer parameter" Error Message

### ISSUE THREAD

**Issue by victorzyang** [CXwudi/comp5903-easy-cucumber#13]
**Describe the bug or Question**
Error message for my method which checks if player dies or not is given below. This method does NOT take an integer parameter. I previously was not getting this error when running my test suite. But all of a sudden, it's coming up for a few of my methods...

<details><summary>scs.comp5903.cucumber.model.exception.EasyCucumberException: EZCU009: Unable to find integer parameter as int: Player dies</summary><p>

Paste your stack trace inside this HTML segment

</p></details>

**(If applicable) Screenshots**

**(For bug report only) Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. macOS 13, Windows Pro 11]
 - Java version: [e.g. Java 11, Java 17]
 - Maven/Gradle version: [e.g. maven 3.8.2, gradle 7.5.1]
 - IDE: [e.g. IntelliJ Ultimate 2022.2.2, Eclipse 2022.6]

**Anything else**
Add any other context about the problem or question here.

**Comment by CXwudi** [comment]
Can you rewrite this issue to include the detailed **To Reproduce** step

**Comment by CXwudi** [comment]
Like I am looking for a issue description as detailed as https://github.com/CXwudi/comp5903-easy-cucumber/issues/12
