### ISSUE TITLE
"Unable to find integer parameter" Error Message

### ISSUE THREAD

**Issue by victorzyang** [CXwudi/comp5903-easy-cucumber#15]
**Describe the bug or Question**
Below is my error message for my method which checks if player dies or not. This method for checking if a player is dead does NOT take an integer parameter at all. I previously was not getting this error when running my test suite. But all of a sudden, it's coming up for a few of my methods...

**(For bug report only) To Reproduce**
1. Create feature file with following scenario:
singlePlayerExpCucumber.feature

@dieWith3SkullsOnFirstRoll
  Scenario Outline: Die with 3 skulls and 5 swords on first roll: player gets a score of 0
    Given Player is "test"
    And Roll is <roll>
    And Fortune Card is "G"
    Then Player dies
    And Expected score is 0
    Examples:
      |roll           |
      |1 1 1 3 3 3 3 3|

2. Create step definition 

package com.a1.yahtzeeGame;

import scs.comp5903.cucumber.model.annotation.*;

import junit.framework.TestCase;

import java.util.*;

public class StepDefSinglePlayerExpCucumber extends TestCase {

  String fortune_card = "";
  int[] dieRoll = new int[8];
  
  Game game = new Game();
  Player p;

  @JGivenStep("Player is {string}")
  public void initializePlayer(String name){
      p = new Player(name);
  }

  @JAndStep("Roll is {int} {int} {int} {int} {int} {int} {int} {int}")
  public void and_roll_is(Integer int1, Integer int2, Integer int3, Integer int4, Integer int5,
                        Integer int6, Integer int7, Integer int8) {
      dieRoll[0] = int1;
      dieRoll[1] = int2;
      dieRoll[2] = int3;
      dieRoll[3] = int4;
      dieRoll[4] = int5;
      dieRoll[5] = int6;
      dieRoll[6] = int7;
      dieRoll[7] = int8;
  }

  @JAndStep("Fortune Card is {string}")
  public void coin_fortune_card_drawn(String fc){
      fortune_card = fc;
  }

  @JThenStep("Player dies")
  public void player_dies(){
      assertTrue(game.isPlayerDead(dieRoll, fortune_card));
  }

  @JAndStep("Expected score is {int}")
  public void get_expected_score(Integer expScore){
      assertTrue(expScore == p.getScore());
  }

}

3. Execute using following code

Path myFeatureFile = Paths.get("src/test/java/com/a1/yahtzeeGame/singlePlayerExpCucumber.feature");
JFeature jFeature = EasyCucumber.build(myFeatureFile, StepDefSinglePlayerExpCucumber.class);
jFeature.executeAll();

**(If applicable) Stack Trace**

<details><summary>logs</summary><p>

Paste your stack trace inside this HTML segment

</p></details>

**(If applicable) Screenshots**

**(For bug report only) Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. macOS 13, Windows Pro 11]
 - Java version: [e.g. Java 11, Java 17]
 - Maven/Gradle version: [e.g. maven 3.8.2, gradle 7.5.1]
 - IDE: [e.g. IntelliJ Ultimate 2022.2.2, Eclipse 2022.6]

**Anything else**
Add any other context about the problem or question here.

**Comment by CXwudi** [comment]
It runs fine at my end, but I restored the JUnit 4 dependencies in your pom.xml file to make it works
