### ISSUE TITLE
The tool doesn't recognize my step definitions

### ISSUE THREAD

**Issue by bloodteller123** [CXwudi/comp5903-easy-cucumber#17]
Oh, I see, you can not mismatch a step keyword. 

For example, if you wrote `And a step` in the feature file, you have to use `@JAndStep` or `@JStep` with `ketword = AND`, using any other annotation will be traded as step definition not implemented

_Originally posted by @CXwudi in https://github.com/CXwudi/comp5903-easy-cucumber/issues/11#issuecomment-1292764206_

**Comment by CXwudi** [comment]
Please rewrite the issue and follow the issue template, simply saying "The tool doesn't recognize my step definitions" doesn't help for debugging

**Comment by bloodteller123** [comment]
One of my scenarios is:
```    
    Given ...
    And...
    When...
    And player 1 rolls "skull skull parrot parrot parrot monkey monkey monkey"
    And player 1 ...
    And player 1 enters islandofskulls
    And player 1 ...
    And player 1 ...
    And player 1 ...
    Then player 1...
    And player 1 ...
    And player 1 ...
```
And I have implemented a respective step definition for "player 1 enters islandofskulls"
```
    @JAndStep("player {int} enters islandofskulls")
    public void playerEntersIslandofskulls(int arg0) {
       .......
    }
```

But the tool is complaining about 
```
EZCU013: Step definition not found for: AndStep(stepString=player 1 enters islandofskulls). Are you sure you implemented this step definition? Or did you forget to make the method public?
```
