### ISSUE TITLE
The tool doesn't recognize my step definitions

### ISSUE THREAD

**Issue by bloodteller123** [CXwudi/comp5903-easy-cucumber#18]
**Describe the bug or Question**
The tool is asking for step definition for a step even though I've implemented it.

**(For bug report only) To Reproduce**
One of my scenarios is:
```    
    Given ...
    And...
    When...
    And player 1 rolls "skull skull parrot parrot parrot monkey monkey monkey"
    And player 1 ...
    And player 1 enters islandofskulls
    And player 1 rerolls sth
    And player 1 ...
    And player 1 ...
    Then player 1...
    And player 1 ...
    And player 1 ...
```
And I have implemented a respective step definition for "player 1 enters islandofskulls"
```
    @JAndStep("player {int} enters islandofskulls")
    public void playerEntersIslandofskulls(int arg0) {
       .......
    }
```

But the tool is complaining about 
```
EZCU013: Step definition not found for: AndStep(stepString=player 1 enters islandofskulls). Are you sure you implemented this step definition? Or did you forget to make the method public?
```

**(If applicable) Screenshots**

**(For bug report only) Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. macOS 13, Windows Pro 11]
 - Java version: [e.g. Java 11, Java 17]
 - Maven/Gradle version: [e.g. maven 3.8.2, gradle 7.5.1]
 - IDE: [e.g. IntelliJ Ultimate 2022.2.2, Eclipse 2022.6]

**Anything else**
https://github.com/bloodteller123/COMP5104A1/blob/1a3b4fede056a9788899f187308dd61eca2e9a52/src/test/resources/FortuneCardTest.feature#L162

**Comment by CXwudi** [comment]
what version are you using rn?

**Comment by bloodteller123** [comment]
0.3.1

**Comment by bloodteller123** [comment]
What's more interesting is that, if I commented out that step (say step 10), the tool will complain 'step def not found' for the next step (i.e, step 11)

**Comment by bloodteller123** [comment]
Ok, i just upgraded to v0.3.3, the problem have not been completely resolved:
```
    @JThenStep("player {int} does skull check")
    public void playerDoesSkullCheck(int arg0) {
..............
    }
```
But the tool is still complaining about not step defi not found.
https://github.com/bloodteller123/COMP5104A1/blob/1a3b4fede056a9788899f187308dd61eca2e9a52/src/test/resources/FortuneCardTest.feature#L166

These steps are from the same scenario. Again, ``` @JThenStep("player {int} does skull check")``` step has been used multiple time in previous scenarios.

**Comment by CXwudi** [comment]
yeah I am also checking what's going on now

**Comment by CXwudi** [comment]
can you paste the error message and stack trace again with 0.3.3?

**Comment by bloodteller123** [comment]
Actually after comparing my cucumber version and ez-cucumber, I noticed that I didn't add 
```
    @JAndStep("player {int} does skull check")
    public void playerDoesSkullCheck(int arg0) {
..............
    }
```
though there already is a @JThenStep version.

I thought If we have a @JThen for one step in one scenario (```Then ABC```), then @JAnd is not needed for the same step in other scenario(```Then XYZ And ABC```). It's true in Cucumber (@Then and @And) but it's not in this tool.

I will close the issue then..

**Comment by CXwudi** [comment]
You mean in Cucumber, using `@And` and `@Then` doesn't matter?

**Comment by bloodteller123** [comment]
I believe so. I have same signature "doesSkullCheck" which were used in Then ... in one scenario, and Then ABC And .... in another scenario but I only declared one @Then step definition and the test passed.
