### ISSUE TITLE
Cannot resolve symbol 'executeAll()'

### ISSUE THREAD

**Issue by victorzyang** [CXwudi/comp5903-easy-cucumber#7]
**Describe the bug or Question**
When I try to run my Cucumber tests by calling executeAll() on my JFeature instance, executeAll() is instead highlighted in red and an error message pops up stating, "Cannot resolve symbol 'executeAll()'"

**(For bug report only) To Reproduce**
4. See error/exception

**(If applicable) Stack Trace**

<details><summary>logs</summary><p>

Paste your stack trace inside this HTML segment

</p></details>

**(If applicable) Screenshots**

**(For bug report only) Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. macOS 13, Windows Pro 11]
 - Java version: [e.g. Java 11, Java 17]
 - Maven/Gradle version: [e.g. maven 3.8.2, gradle 7.5.1]
 - IDE: [e.g. IntelliJ Ultimate 2022.2.2, Eclipse 2022.6]

**Anything else**
Add any other context about the problem or question here.

**Comment by CXwudi** [comment]
Can you paste your pom.xml file here and a screenshot of where you called the executeAll() method?

**Comment by victorzyang** [comment]
Here is a screenshot of where I call the executeAll() method:

![JFeature executeAll() Cannot resolve symbol error](https://user-images.githubusercontent.com/43623165/198145256-d23b385c-42f9-4786-9052-31d26cc6e05e.png)

Here is my pom.xml file:

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.a1</groupId>
  <artifactId>yahtzeeGame</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>yahtzeeGame</name>
  <url>http://maven.apache.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>18</maven.compiler.source>
        <maven.compiler.target>18</maven.compiler.target>
    </properties>

  <repositories>
    <repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
    </repository>
  </repositories>
	
  <dependencies>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>5.8.2</version>
    </dependency>

    <dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-suite</artifactId>
      <version>1.9.0</version>
    </dependency>

    <dependency>
      <groupId>io.cucumber</groupId>
      <artifactId>cucumber-java</artifactId>
      <version>7.3.4</version>
    </dependency>

    <dependency>
      <groupId>io.cucumber</groupId>
      <artifactId>cucumber-junit-platform-engine</artifactId>
      <version>7.3.4</version>
    </dependency>

    <dependency>
      <groupId>com.github.CXwudi</groupId>
      <artifactId>comp5903-easy-cucumber</artifactId>
      <version>0.3.1</version>
    </dependency>

  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.0.0-M5</version>
        <configuration>
          <properties>
            <configurationParameters>
              cucumber.junit-platform.naming-strategy=long
            </configurationParameters>
          </properties>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>

**Comment by CXwudi** [comment]
Oh, I mean, you can't execute method in class body. That's Java basic knowledge.

But I will improve the document so that JUnit user knows where to add the code in JUnit
